# Generated by Django 3.2.21 on 2023-09-26 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 26, 14, 16, 21, 43862, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
