# Generated by Django 3.2.21 on 2023-09-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
