# Generated by Django 3.2.21 on 2023-09-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_remove_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Lebanese',
            field=models.BooleanField(default=False),
        ),
    ]
