# Generated by Django 3.2.21 on 2023-09-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_contact_lebanese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Lebanese',
            field=models.BooleanField(default=True),
        ),
    ]
