# Generated by Django 3.2.21 on 2023-09-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_alter_contact_lebanese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Lebanese',
        ),
    ]
