# Generated by Django 3.2.21 on 2023-10-03 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0006_remove_contact_lebanese'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.CharField(default=datetime.datetime(2023, 10, 3, 10, 13, 33, 595478, tzinfo=utc), max_length=4),
            preserve_default=False,
        ),
    ]
