# Generated by Django 3.2.21 on 2023-10-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0007_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
    ]
