# Generated by Django 3.2.21 on 2023-10-03 10:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0008_remove_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 10, 3, 10, 22, 31, 62759, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
